### ISSUE TITLE
Opdatering til formular.css

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#104]
Hej Karsten.
Jeg oplever på IE10, at tekstfelter med regular expressions på forsvinder, når man først har indtastet en ikke-valid værdi, for derefter at indtaste en valid værdi. Det lader til, at IE ikke kan finde ud af:
<div class="valuediv valid">, hvis der ikke er en css-værdi for 'valid'. Derfor vil jeg gerne have indført følgende i formular.css, så det altid kommer med ud:
.valid {
    width: 450px;
}

**Comment by karstenpihl** [comment]
Dette mener jeg er løst. Generelt kan der være behov løbende tilpasningen til forskellige browsere.
