### ISSUE TITLE
Mulighed for buffer i forbindelse med maptool select

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#106]
Ved at sætte et select maptool ind er det muligt at vælge geometry på baggrund af en datasource. Det er bare meget besværligt med et stregtema. Det kunne være fint at man i config filen kan sætte en buffer størrelse

**Comment by karstenpihl** [comment]
Jeg mener at dette allerede kan lade sig ved at tilpasse konfigurationen i SpS
