### ISSUE TITLE
Problemer med submitpages og reportprofile

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#107]
Såfremt jeg udkommenterer reportprofile, så fejler mine submitpages. Ved henvendelse drejer det sig om vandvaerk.xml

**Comment by karstenpihl** [comment]
Det skyldes at den page, der kaldes kræver at der er angivet en profil eller at profilen findes. Problemet kan være at pagen kaldes med en default profil, der ikke findes.
