### ISSUE TITLE
Udokumenteret feature

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#108]
Det er muligt, at vi ikke har den seneste information (readme.md) i forbindelse med VIRK-udgaven, men vi plejer at skulle tegne i kortet, såfremt det er med. 
Med den version vi kører med, er det nødvendigt at skrive følgende, før det registreres, om der er tegnet i kortet:

``` xml
<map required='true'/>
```

Og det kan jeg ikke finde dokumenteret i readme.md

Mvh.
Kåre

**Comment by karstenpihl** [comment]
Det burde blive registreret at der bliver tegnet i kortet men måske skal det undersøges nærmere. Hvis det er tilfældet, skal det selvfølgelig rettes til.

I forbindelse med Virk integrationen er der blevet tilføjet mulighed for required="true" på alle elementer, herunder også kortet.
