### ISSUE TITLE
File typen og ID

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#109]
Hej Karsten.
Hvis man har en "file"-type i sin formular, som gerne må være tom og man glemmer at sætte et ID for feltet, så fejler formularen, hvis der ikke er angivet en fil. Eksempel:

``` html
<input type="file"  displayname="Der skal vedhæftes fil." urlparam="bilag" />
```

Da der ikke er en regexp på dette felt kan det efterlades tomt. Gøres det vil man få følgende fejl (forkortet):
com.carlbro.jdaf.expression.ExprException: Error in expression. No value for variable name: bilag/Stacktrace:/ com.carlbro.jdaf.expression.Variable.evaluationException(Variable.java:170)/ com.carlbro.jdaf.expression.Variable.getIndexForName(Variable.java:160)/ com.carlbro.jdaf.expression.Variable.isString(Variable.java:68)/ 

Ændres feltet til:

``` html
<input type="file"  displayname="Der skal vedhæftes fil." urlparam="bilag"  id="bilag" /> 
```

så går det godt - også selvom der ikke er angivet en fil.

Mvh.
Kåre

**Comment by karstenpihl** [comment]
Jeg lukker issuet pga. manglende aktivitet. Hvis der fortsat er nogen, der oplever dette problem, så kan det åbnes igen.
