### ISSUE TITLE
Radiobutton kan ikke bruges til condition

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-formular#110]
Værdien (value) for radiobutton når man afsluteret formular er OK, men den bliver ikke ændret med det samme, derfor kan desværre ikke bruges til condition.

```(xml)
<input id="rb" type="radiobutton" defaultvalue="nej" onchange="visValue('rb')">
                <option value="ja" name="Ja"/>
                <option value="nej" name="Nej"/>
</input>
<input id="txtbox" type="textarea" condition="jQuery('#rb').val() == 'ja'"/>
```

```(js)
function visValue(id){
	var idValue = jQuery('#'+id).val();
	alert('value:' + idValue);
}	
```

**Comment by gis-haderslev** [comment]
![radiobutton_ja](https://cloud.githubusercontent.com/assets/8122296/6842900/869fe722-d39d-11e4-844d-e9ba411050a5.PNG)
![radiobutton_nej](https://cloud.githubusercontent.com/assets/8122296/6842899/869fa456-d39d-11e4-92a7-e9735484d60e.PNG)

**Comment by karstenpihl** [comment]
Man man ikke bare sige .val(). Du skal i stedet bruge:
```javascript
function visValue(id){
    var idValue = jQuery('input#'+id+':checked').val();
    alert('value:' + idValue);
}
```

**Comment by gis-haderslev** [comment]
Mange tak for svaret. Har tilpasset min condition til
'''(xml)
<input id="txtbox" type="textarea" condition="jQuery('input#rb:checked').val() == 'ja'"/>
'''
og  det virker nu.
