### ISSUE TITLE
Kald af funktion ved formularets start

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-formular#112]
Man kan godt kælde js funktion "onchange" eller "onkeyup".
Hvordan kan jeg kalde funktion når jeg starter et formular? noget som onload?

**Comment by moelgaard730** [comment]
Hej Haderslev.

Øverst i jeres JS-fil skriver I følgende:
window.onload = function() 
{
	setTimeout(function() {<funktionsnavn>},200);
}
De 200 er antallet af milisekunder der skal gå, før funtionen <funktionsnavn> bliver eksekveret. Er det en side med mange felter/data, er det muligt, at tiden skal sættes op til 500.
Et konkret eksempel:
window.onload = function() 
{
	setTimeout(function() {setDagsDato(true)},200);
}
function setDagsDato(visDagsDato)
{
	var d = new Date();
	var strDate = d.getDate() + '/' + (d.getMonth()+1) + "-" + d.getFullYear();
	jQuery('#dagsdato_hidden').val(strDate);
       if (visDagsDato)
       {
	     jQuery('#dagsdato').val(strDate);
      }
}
