### ISSUE TITLE
Udvidet håndtering af fejl

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#114]
Hej Karsten.

Jeg vedhæfter en udgave af formular.js i en mail direkte til dig, hvor jeg har lavet nogle ændringer. Baggrunden er, at vi gerne vil kunne håndtere fejl på en lidt mere smart måde. Dette er tænkt i stil med submitpages, blot kaldt errorpages. På denne måde kan vi selv definere om vi vil sende en mail, skrive til databasen eller andet, i det tilfælde der opstår en fejl.
De steder jeg har rettet/tilføjet er markeret med kommentaren 
//af KMR
Jeg er i tvivl om jeg har lavet rettelserne i den seneste version af formularmodulet - du har vist lavet et merge for nylig, men lads os vende det over telefonen ved førstgivende lejlighed.

I config filen vil errorpages se således ud:
        <errorpages>
            <page>formular.test2.errorhandling</page>
        </errorpages>

**Comment by karstenpihl** [comment]
Dette mener jeg er implementeret.
