### ISSUE TITLE
Problemer med ErrorPages og multiple geometrier

### ISSUE THREAD

**Issue by GIS-RandersKommune** [Septima/spatialsuite-formular#123]
Hej Karsten.

Jeg har fundet en fejl i forbindelse med formularmodulet, errorpages og multiple geometrier.
Problemet ligger i, at anvendes der multiple geometrier, så kommer svaret fra formular.geometry.save tilbage asynkron og frCounter er derfor -1 og showDone bliver aldrig kaldt. Jeg har en løsning klar til at lægge i GitHub i morgen tidlig

**Comment by karstenpihl** [comment]
Jeg mener at dette er løst. Hvis det fortsat er et problem, så kan issuet åbnes igen.
