### ISSUE TITLE
Rettelse til formular.css

### ISSUE THREAD

**Issue by GIS-RandersKommune** [Septima/spatialsuite-formular#127]
Hej Karsten.
I formular.css - message_loading mangler der vist et 'px efter det første 0 i background-position

Mvh.
Kåre

**Comment by karstenpihl** [comment]
Nej, det er ikke nødvendigt at angive enhed når værdien er 0.

**Comment by GIS-RandersKommune** [comment]
Hej Karsten.
Jeg ved ikke om det er min version af Chrome der er årsagen, men jeg vedhæfter lige to billeder. "med_px.png" viser hvordan spinner´en ser ud med '0px 0px' og "uden_px.png" viser, hvordan det ser ud med '0 0px'.
uden_px viser, hvordan ca. halvdelen af spinner´en er skåret af, fordi den er rykket ned.

Mvh.
Kåre
![uden_px](https://cloud.githubusercontent.com/assets/13584505/10387540/934e4a4e-6e62-11e5-8605-94fba2beb85b.png)
![med_px](https://cloud.githubusercontent.com/assets/13584505/10387541/934e730c-6e62-11e5-8baa-f7c01356bd4e.png)

**Comment by karstenpihl** [comment]
Det første tal er "left" og det andet tal er "top". I dit eksempel er det top, der bliver ændret, så det virker meget mærkeligt. Hvis jeg lavet et helt rent eksempel, så kan jeg ikke genskabe problemer. Kan du prøve med din browser her: http://www.w3schools.com/cssref/tryit.asp?filename=trycss_background-position_percent og se om du får samme fejl på et meget simpel eksempel?

**Comment by GIS-RandersKommune** [comment]
Hej Karsten.

Jeg fik vidst pillet ved to ting på en gang og forvekslede resultatet. Jeg kan godt se nu, at "0 0px" eller "0 10px" virker. Det jeg egentlig gerne vil have ændret er "0 10px" til "0 0px", såfremt det ikke giver problemer andre steder. Så kommer spinner´en til at sidde ordentligt i forhold til teksten. Alternativt kan jeg bare lave min egen css-fil og ændre det der.

Mvh.
Kåre
