### ISSUE TITLE
Mulighed for IKKE at lave query i forbindelse med tegning af egen geometri

### ISSUE THREAD

**Issue by GIS-RandersKommune** [Septima/spatialsuite-formular#141]
I forbindelse med brugen af maptools sker altid en featureChanged, hvilket igen kalder query-metoden.
Der kan være enkelte situationer, hvor tegning i kortet IKKE skal kalde query-metoden.
Dette kan klares på følgende måde (omend den ikke er særlig general)
maptool elementet har allerede 'options' tag´et (omend det ikke er dokumenteret). Med options="disablequery" i config-filen (eks:

``` xml
<maptool displayname="Tegn en strækning" name="line" options="disablequery"/>
```

kan man omkring linje 2532 (query metoden) tilføje:

``` javascript
var curMT = this.currentMapTool;
var curOption = this.mapbuttons[curMT].options ? this.mapbuttons[curMT].options : null;
if (curOption != null && curOption == 'disablequery') {
    return;
}
```

Hvilket bremser selve query kaldet.

Men det er som udgangspunkt ikke særlig generelt. Giver det mening og kan det eventuelt gøres mere generelt.
Mvh.
Kåre

**Comment by karstenpihl** [comment]
Hvilke andre ting kunne man forestille sig at man gerne ville disable når man brugte et maptool?

Kunne man ikke vende den om, så man satte conditions på en query? Her kunne man så angive en condigtion der hed  "this.currentMapTool !== 'line'" eller noget i den stil. Det vil gøre query mere fleksibel og den kunne være betinget af mange ting.

**Comment by GIS-RandersKommune** [comment]
Hej Karsten og tak for input´et
Mht. "Hvilke andre ting kunne man forestille sig at man gerne ville disable når man brugte et maptool?", så var min tanke, at når jeg nu bruger options tag´et, så kunne der i fremtiden komme andre options, som så igen vil mudre koden til med if-sætninger. 
Men dit bud med en condition på selve query´en er netop en general løsning, der er mere fleksibel end mit første bud.
Jeg tænker det implementeret således:
`<conflicts urlparam="konflikttekst1" id="dyrehegn" displayname="Dyrehegn:" targerset="dyrehegn" condition="this.currentMapTool !== 'line'"/>`
Er det også din tanke eller?

Mvh.
Kåre

**Comment by karstenpihl** [comment]
Ja, præcist. Der skal bare stå formular i stedet for this.

**Comment by karstenpihl** [comment]
Jeg lukker dette issue, da det ser ud til at være løst. Hvis det stadig er et behov, kan issuet åbnes igen.
