### ISSUE TITLE
Problem med '&' symbolen i 'dropdown' eller i 'input' feltet

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-formular#145]
Så snart man har '&' symbolen i 'dropdown' eller i 'input' felterne, bliver sætningen klippet ved 'write' comando.
 F.x. når jeg vælger i dropdown-menuen eller taster ind i en input-felt 'Mad & Drikke' bliver kun 'Mad' gemt i tabellen.

**Comment by karstenpihl** [comment]
Jeg synes at vi har snakket om dette. Hvis det stadig er aktuelt, så tilføj meget gerne en konfiguration, så det er nemt at genskabe problemet.

**Comment by karstenpihl** [comment]
Jeg lukker dette issue, da der ikke er sket noget i lang tid og måske er løst. Opret et nye issue, hvis det stadig er et problem.
