### ISSUE TITLE
Send genereret PDF-kvitering per mail

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-formular#149]
Hvordan kan jeg sende den genererede PDF-kvitering per mail til mig selv.

**Comment by gis-haderslev** [comment]
Jeg har fundet script på nettet, men den bruger SMTP er ikke sikkert at den vil køre.
Kan vi bestille function, der kan sende mail via vores Exchange?

**Comment by karstenpihl** [comment]
Der er forskellige måder at gøre det på. Når I har jeres Exchange server, har I garanteret også en SMTP server. Så start med at snakke med jeres IT-afdeling om det. De bruger den sikkert i andre tilfælde. Hvis I har det, så kan I evt. bruge de script som du har fundet.

Vi har også en funktion, der kan sende mails, inkl. vedhæfte dokumenter. Det er et lille program, som vi installere på serveren. Dette er et program, der er uafhængigt af Spatial Suite og kan derved bruges til alt muligt.

Der findes også forskellige muligheder direkte i Postgres, der kan det. Vi har bruge en som vi synes er meget god. Jeg mener også at Sweco har lavet en der fungere som en funktion i Postgres. Jeg ved ikke om den kan vedhæfte dokumenter.

**Comment by gis-haderslev** [comment]
Tak for svar.
