### ISSUE TITLE
Billede i formularmodul

### ISSUE THREAD

**Issue by Dorthe-Bak-Toefting** [Septima/spatialsuite-formular#150]
Er det muligt at indsætte et billede i en formular (ikke at forveksle med upload af et billede). Jeg har behov for at få sat et billede ind som skal fungere som en hjælp for indberetter mht hvorvidt de har en brønd el en boring på deres ejendom.

Anden bedste løsning er et link til billedet hvis førstnævnte ikke kan lade sig gøre.

Jeg har forsøgt mig lidt frem men uden held.
/Dorthe - Silkeborg Kommune

**Comment by karstenpihl** [comment]
Jeg ved ikke om dette stadig er aktuelt, men jeg vil mene at det er muligt at gøre i dag. Det gøres ved at indsætte HTML direkte i konfigurationen i stil med dette:
````
<input type="text" displayname="&lt;img class='custom_billede' src='https://webkort.kommune.dk/billede.png'/&gt;"/>
````
