### ISSUE TITLE
Udfordringer med tag´et required="true"

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#151]
Hej Karsten.
Jeg oplever, at required="true" giver bøvl, hvis man tab´er sig fra felt A til felt B, hvor begge er required.
![formular_problem1](https://cloud.githubusercontent.com/assets/6029987/25948640/b4f501ea-3654-11e7-83a6-0ab549a0598c.png)
![formular_problem2](https://cloud.githubusercontent.com/assets/6029987/25948639/b4f43350-3654-11e7-8b90-5ae3ca7ffa77.png)
På skærmdump: formular_problem1 er jeg tab´et over et textarea, der er required og ned i et dato felt, der er required. Men fejlbeskeden stå udfor dato feltet (også på skræmdump: formular_problem2), når jeg tab´er videre - kan der gøres noget ved det?

Mvh.
Kåre

**Comment by moelgaard730** [comment]
Rettelse: På skærmdump 2 har jeg indtastet en tekst i textarea´et - men det først derefter, at fejlbeskeden forsvinder (og fejlbeskeden hænger som det kan ses på dato-feltet - til trods for, at dato´en er korrekt)

**Comment by karstenpihl** [comment]
Hvis dette stadig er aktuelt, så må du meget gerne oprette et PR med en løsning, eller tilføjet en konfiguration, der gør det muligt nemt at reproducere fejlen.

**Comment by karstenpihl** [comment]
Jeg lukker dette issue pga. manglende aktivitet. Opret nyt issue hvis der er nogen, der oplever noget lignende.
