### ISSUE TITLE
Udfordringer med NemLogin

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#152]
Hej Karsten.
Oprindeligt så formular.xsl således ud

`                <xsl:if test="$RequestId != ''">
                nemlogin = {
                    ssp: '<xsl:value-of select="$SignedSignatureProof"/>',
                    reqid: '<xsl:value-of select="$RequestId"/>',
                    signtext: '<xsl:value-of select="$SignText"/>',
                    url_params: '<xsl:value-of select="$string_params"/>'
                };</xsl:if>
`

Det giver, så vidt jeg kan se problemer i det JS, som SWECO lavede til NemLogin - det ser ud som følger:

`		if(nemlogin.ssp.length > 0 ){
			//hvis den kommer tilbage med en status=canceled kan urlparametrene også bruges til at udfylde formularen, så brugeren ikke skal starte forfra
			nem_submit();
		}else{
	
			getCprNavnFromSaml();
			getCprNrFromSaml();
			
			//fjerner formularmodulets standard sendfunktionalitet
			jQuery('#sendbutton').unbind( "click" );
			
			//overskriver med nem signering
			jQuery('#sendbutton').click(function() {sign()});
		}`

Men eftersom nemlogin-variablen ikke er oprettet første gang man kommer forbi siden, så fejler JavaScriptet og click-funktionen på send-knappen bliver ikke overskrevet (else-delen)
Jeg forestiller mig en løsning ala:

`               var nemlogin = {
                    ssp: '',
                    reqid: '',
                    signtext: '',
                    url_params: ''};
					
                <xsl:if test="$RequestId != ''">
                nemlogin = {
                    ssp: '<xsl:value-of select="$SignedSignatureProof"/>',
                    reqid: '<xsl:value-of select="$RequestId"/>',
                    signtext: '<xsl:value-of select="$SignText"/>',
                    url_params: '<xsl:value-of select="$string_params"/>'
                };</xsl:if>`

På den måde sker der ikke fejl i JavaScriptet.
Hvorfor jeg ikke fangede dette sidste år skal jeg lade være usagt, og om der findes en bedre løsning vil jeg lade være op til dig.
Jeg er ikke kommet i sving med GitHub i forhold til SWECO, men hvis du ikke har tid, så send mig løsningen - så skal jeg prøve at gøre noget ved det.

Mvh.
Kåre

**Comment by dk-moelgaard75** [comment]
Hej Karsten.

Jeg kan se, at dette issue er oprettet med den bruger jeg anvendt mens jeg arbejde ved Randers Kommune. Den har jeg ikke adgang til mere - kan du lukke issuet?
