### ISSUE TITLE
Cast til geometry med en **if then else endif** i update SQL

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/spatialsuite-formular#153]
Jeg har formular med adressefelt
```
<sql command="write">
INSERT INTO formular.test(adresse, wkb_geometry) 
VALUES( 
	[string: if IsDefined(adresse) then adresse else null endif],
	[geometry: ToGeometry(adresse_wkt)]
);
</sql>
```
og vil opdatere adressen i en anden formular, som det kræver at jeg opdatere også adressens geometri, men kun hvis adressen blev ændret. Til formålet har jeg urlparam=**adresse** som husker adressen og urlparam=**shape_wkt** som husker den geometrien på den.

Kan ikke få **update** til at vælge mellem de to geometrier.
```
<sql command="update">
UPDATE formular.test SET 
       adresse = [string: if IsDefined(adresse) then adresse else null endif],
       wkb_geometry = [geometry: ToGeometry(if IsDefined(adresse_wkt) then adresse_wkt else shape_wkt endif)]
WHERE ogc_fid = [ogc_fid];
</sql>
```

 SpatialSuite broker sig med:
  **_Value, function or leftpar. expected. Expression: 'ToString( ToGeometry(if IsDefined(adresse_wkt) then adresse_wkt else shape_wkt endif))'. Last symbol "if"._**

Har prøvet med :
```
wkb_geometry = [geometry: if IsDefined(adresse_wkt) then ToGeometry(adresse_wkt) else ToGeometry(shape_wkt) endif)]
```
Samme efekt:
 **_Value, function or leftpar. expected. Expression: 'ToString( if IsDefined(adresse_wkt) then ToGeometry(adresse_wkt) else ToGeometry(shape_wkt) endif))'. Last symbol "if"._**

Det kører fint med 
```wkb_geometry = [geometry: ToGeometry(adresse_wkt)]```
eller med 
```wkb_geometry = [geometry: ToGeometry(shape_wkt)]```

Hvordan kan jeg caster til **geometry** med en **if then else endif**  ? 
Der er jo ingen problem med **number** og **string** data typerne.

**Comment by karstenpihl** [comment]
Du har en ) for meget til sidst i:
````
wkb_geometry = [geometry: if IsDefined(adresse_wkt) then ToGeometry(adresse_wkt) else ToGeometry(shape_wkt) endif)]
````
Men det er ikke sikkert at det er det. Det kan være at "adresse_wkt" er defineret men bare ikke en valid WKT. Kan du se i requestloggen i /admin eller direkte i browseren under developertoolet -> network.

**Comment by gis-haderslev** [comment]
"adresse_wkt" kommer fra geosearch og jeg går ud fra at den bliver først defineret først når jeg indtaster og udvælger adressen
```
<geosearch urlparam="adresse" resources="Adresser" usegeometry="true"/>
```
hvor "shape_wkt" er den gamle som jeg indlæser ved starten af min formular
```
<rowlist name="result" pcolid="{A1EA7C68-42A0-45D9-B277-A75640E73DCC}">
 <row name="result" pcolid="{40B79D71-A3C7-4E54-8DB9-35BEB40E424F}">
  <col name="ogc_fid">1</col>
  <col name="adresse">Rådhuscentret 3, 6500 Vojens</col>
  <col name="shape_wkt">POINT (529324 6122949)</col>
 </row>
</rowlist>
```

**Comment by karstenpihl** [comment]
Kan du se om de rent faktisk bliver sendt med når pagen bliver kaldt og hvilken værdi de har?

Prøv med:
````
wkb_geometry = [geometry: if IsDefined(adresse_wkt) then adresse_wkt else shape_wkt endif]
````

**Comment by gis-haderslev** [comment]
```
---------------------------------------------
Input:
*** Row {AE5AA922-2D5A-4423-957A-1295414D5896}

  index  name                 datatype  value
------------------------------------------------------------------------
  0      datasource           String    "ds-test"
  1      command              String    "update"
  3      srs                  String    "25832"
  4      ogc_fid              String    "1"
  9      adresse              String    "Simmerstedvej 1A, 6100 Haderslev"
  11     page                 String    "formular.update.test"
  18     outputformat         String    "json"
  19     formular             String    "test_edit"
  21     adresse_wkt          String    "POINT(530117.0 6123003.0)"
  22     shape_wkt            String    "POINT (529324 6122949)"
------------------------------------------------------------------------
```

**Comment by gis-haderslev** [comment]
Samme fejl 
 	**_System error 'java.lang.Exception: Error executing command 'update' on datasource 'ds-test'. com.carlbro.jdaf.expression.ExprException: Value, function or leftpar. expected. Expression: 'ToString( if IsDefined(adresse_wkt) then adresse_wkt else shape_wkt endif)'. Last symbol "if". Last position 11'_**

**Comment by gis-haderslev** [comment]
<output>
	<rowlist name="result" pcolid="{155597D5-3B17-4DF8-8845-3416E755300D}">
		<row name="result" pcolid="{8C253C78-8F51-4BE2-8609-29BCC8833813}">
			<col name="ogc_fid">2</col>
			<col name="adresse">Brombærvej 45, 6100 Haderslev</col>
			<col name="shape_wkt">POINT (531033 6120347)</col>
		</row>
	</rowlist>
</output>

<input>
    <row name="result" pcolid="{C6217290-ED5E-42AD-85A5-E0A474E4A235}">
        <col name="datasource">ds-test</col>
        <col name="command">update</col>
        <col name="srs">25832</col>
        <col name="ogc_fid">2</col>
        <col name="adresse">Simmerstedvej 10A, 6100 Haderslev</col>
        <col name="page">formular.update.test</col>
        <col name="outputformat">json</col>
        <col name="formular">test_edit</col>
        <col name="adresse_wkt">POINT(530161.0 6123044.0)</col>
        <col name="shape_wkt">POINT (531033 6120347)</col>
    </row>
</input>

**Comment by karstenpihl** [comment]
Så ved jeg det ikke lige hvorfor. Men vi kan lave det i pagen i stedet for i datasource. Jeg kan se at du kalder pagen "formular.update.test" (det er ikke en jeg har). Dette er angivet i konfigurationen til denne formular. Her kan du angive en anden page, der ser ud i stil med denne:

    <page name="formular.update-test2" contenttype="application/json" sessionrequired="true">  
        <data handler="datasource" operation="execute-command">
            <url-parameters>
                <url-parameter name="datasource" value="ABC"/>
                <url-parameter name="command" value="update"/>
                <url-parameter name="shape_wkt">if IsDefined(adresse_wkt) then adresse_wkt else shape_wkt endif</url-parameter>
            </url-parameters>
        </data>
    </page>

**Comment by gis-haderslev** [comment]
tak, jeg prøver med det samme

**Comment by gis-haderslev** [comment]
Mange tak ! Det funger. Jeg stiller spørgsmål ved lejlighed til SWECO angående den anden fejl.
