### ISSUE TITLE
Udfordring med NemLogin i skin-udgaven

### ISSUE THREAD

**Issue by dk-moelgaard75** [Septima/spatialsuite-formular#156]
Hej Karsten.
i formular-skin.xsl mangler:
```
var nemlogin = {
    ssp: '',
    reqid: '',
    signtext: '',
    url_params: ''
};
<xsl:if test="$RequestId != ''">
    nemlogin = {
        ssp: '<xsl:value-of select="$SignedSignatureProof"/>',
        reqid: '<xsl:value-of select="$RequestId"/>',
        signtext: '<xsl:value-of select="$SignText"/>',
        url_params: '<xsl:value-of select="$string_params"/>'
    };
</xsl:if>
```
for at NemLogin delen virker.
Jeg vil gerne lave arbejdet med at få XSL opdateret (inklusiv issue #152), hvis du har travlt.
Mvh.
Kåre

**Comment by karstenpihl** [comment]
Du er meget velkommen til at lave det. Opret et pull request med dine rettelser, så får vi dem ind.

Men hvor bliver den globale variabel `nemlogin` brugt? Kan du ikke lægge koden ind i formularmodulet? Så kan jeg se hvad det er der sker. Generelt, så vil jeg foreslå at du laver koden defensiv, så den kan håndtere at `nemlogin` ikke findes. Med ovenstående tilføjelse, vil der stå "nemlogin" i samtlige formularer, til trods for at det kun er et fåtal, der overhovedet har brug for det.

**Comment by karstenpihl** [comment]
Jeg har tilføjet ovenstående kode til https://github.com/Septima/spatialsuite-formular/tree/nemlogin,  som du kan arbejde videre med i forbindelse med #152.

Du bør håndtere at nemlogin ikke er defineret i den kode (som jeg ikke kan se). Det gøres meget nemt ved i toppen af din fil at skrive:
````
if (typeof nemlogin === 'undefined') {
    var nemlogin = {
        ssp: '',
        reqid: '',
        signtext: '',
        url_params: ''
    };
}
````

**Comment by dk-moelgaard75** [comment]
Hej Karsten.
Eftersom du har rettet formular-skin.xsl og jeg har rettet SWECO´s nemlogin.js fra
`if(nemlogin.ssp.length > 0 )`
til
`if(typeof nemlogin !== 'undefined' && nemlogin.ssp.length > 0 )`
tænker jeg, at #152 kan lukkes. 
Jeg tillader mig lige at oprette et nyt issue i relation til nemlogin. Jeg prøver i den forbindelse at lave en tilføjelse til nemlogin branchen.

**Comment by karstenpihl** [comment]
Det lyder godt. Du lukker bare #152.
