### ISSUE TITLE
MonthPicker

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#80]
Jeg har fundet en MonthPicker på internettet (http://lucianocosta.info/jquery.mtz.monthpicker/) som jeg har testet i en formular og umiddelbart virker den fin. I kan kigge på den ved lejlighed  - når I har tid :-). Kildekoden ligger på GitHub her:
https://github.com/lucianocosta/jquery.mtz.monthpicker

**Comment by karstenpihl** [comment]
Det vil kunne laves på et par timer. Genåben issuet hvis der er nogen, der ønsker denne funktionalitet.
