### ISSUE TITLE
Forbedring i forbindelse med final.jsp og gammel metode til submitpages

### ISSUE THREAD

**Issue by moelgaard730** [Septima/spatialsuite-formular#97]
Omkring linje 1707 testes der på, om final.jsp returenere OK. Hvis resultatet er forskellig fra OK printes umiddelbart den forkerte message. Det betyder blandt andet, at der kommer to "Ansøgning er nu registreret" beskeder

**Comment by karstenpihl** [comment]
Hvis dette stadig er et issue, så åben issuet igen og beskriv hvordan det kan genskabes.
